// Auto-generated — do not edit manually. Run scripts/generate_thumbs.py to refresh.
// Thumbs estaticas (1o frame, JPEG) dos GIFs do catalogo — mesmas chaves do gifAssets.
 
// prettier-ignore
export const thumbAssets: Record<string, ReturnType<typeof require>> = {
  'ABDOMEN CORE (1)/ABS alternando pernas.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/ABS alternando pernas.jpg'),
  'ABDOMEN CORE (1)/ABS banco declinado completo.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/ABS banco declinado completo.jpg'),
  'ABDOMEN CORE (1)/Abs banco.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/Abs banco.jpg'),
  'ABDOMEN CORE (1)/Abs bola flexao de quadril.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/Abs bola flexao de quadril.jpg'),
  'ABDOMEN CORE (1)/ABS com flexao lateral.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/ABS com flexao lateral.jpg'),
  'ABDOMEN CORE (1)/Abs lateral.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/Abs lateral.jpg'),
  'ABDOMEN CORE (1)/ABS maquina.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/ABS maquina.jpg'),
  'ABDOMEN CORE (1)/ABS obliquo.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/ABS obliquo.jpg'),
  'ABDOMEN CORE (1)/ABS polia alta 2.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/ABS polia alta 2.jpg'),
  'ABDOMEN CORE (1)/ABS polia alta.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/ABS polia alta.jpg'),
  'ABDOMEN CORE (1)/ABS remador pernas extendidas.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/ABS remador pernas extendidas.jpg'),
  'ABDOMEN CORE (1)/conventional-sit-up.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/conventional-sit-up.jpg'),
  'ABDOMEN CORE (1)/Crunch 4.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/Crunch 4.jpg'),
  'ABDOMEN CORE (1)/Crunch pernas elevadas.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/Crunch pernas elevadas.jpg'),
  'ABDOMEN CORE (1)/Crunch reverso.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/Crunch reverso.jpg'),
  'ABDOMEN CORE (1)/Dead bug.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/Dead bug.jpg'),
  'ABDOMEN CORE (1)/Flexao de quadril banco.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/Flexao de quadril banco.jpg'),
  'ABDOMEN CORE (1)/Flexao lateral bola.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/Flexao lateral bola.jpg'),
  'ABDOMEN CORE (1)/obliquo polia baixa.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/obliquo polia baixa.jpg'),
  'ABDOMEN CORE (1)/Prancha frente tras.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/Prancha frente tras.jpg'),
  'ABDOMEN CORE (1)/weightedsitups.gif': require('../../../../assets/thumbs/ABDOMEN CORE (1)/weightedsitups.jpg'),
  'COSTAS E TRAPÉZIO (1)/band-assisted-pull-up.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/band-assisted-pull-up.jpg'),
  'COSTAS E TRAPÉZIO (1)/banded-wide-grip-row.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/banded-wide-grip-row.jpg'),
  'COSTAS E TRAPÉZIO (1)/Barra fixa nuca.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/Barra fixa nuca.jpg'),
  'COSTAS E TRAPÉZIO (1)/cable-face-pull.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/cable-face-pull.jpg'),
  'COSTAS E TRAPÉZIO (1)/cable-wide-grip-row.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/cable-wide-grip-row.jpg'),
  'COSTAS E TRAPÉZIO (1)/Encolhimento 3.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/Encolhimento 3.jpg'),
  'COSTAS E TRAPÉZIO (1)/Pulldown1.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/Pulldown1.jpg'),
  'COSTAS E TRAPÉZIO (1)/Puxada alta tradicional.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/Puxada alta tradicional.jpg'),
  'COSTAS E TRAPÉZIO (1)/Puxada alta triangulo.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/Puxada alta triangulo.jpg'),
  'COSTAS E TRAPÉZIO (1)/Puxada unilateral 1.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/Puxada unilateral 1.jpg'),
  'COSTAS E TRAPÉZIO (1)/Remada alta.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/Remada alta.jpg'),
  'COSTAS E TRAPÉZIO (1)/Remada apoio banco inclinado.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/Remada apoio banco inclinado.jpg'),
  'COSTAS E TRAPÉZIO (1)/Remada cabo.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/Remada cabo.jpg'),
  'COSTAS E TRAPÉZIO (1)/Remada com halteres.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/Remada com halteres.jpg'),
  'COSTAS E TRAPÉZIO (1)/Remada inclinada.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/Remada inclinada.jpg'),
  'COSTAS E TRAPÉZIO (1)/Remada maquina.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/Remada maquina.jpg'),
  'COSTAS E TRAPÉZIO (1)/Remada unilateral.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/Remada unilateral.jpg'),
  'COSTAS E TRAPÉZIO (1)/single-arm-dumbbell-row.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/single-arm-dumbbell-row.jpg'),
  'COSTAS E TRAPÉZIO (1)/t-bar-row-muscles.gif': require('../../../../assets/thumbs/COSTAS E TRAPÉZIO (1)/t-bar-row-muscles.jpg'),
  'Gifs - Bonus/Biceps/biceps concentrado unilateral no cross.gif': require('../../../../assets/thumbs/Gifs - Bonus/Biceps/biceps concentrado unilateral no cross.jpg'),
  'Gifs - Bonus/Biceps/biceps unilateral polia alta cross.gif': require('../../../../assets/thumbs/Gifs - Bonus/Biceps/biceps unilateral polia alta cross.jpg'),
  'Gifs - Bonus/Biceps/rosca  direta no banco scort.gif': require('../../../../assets/thumbs/Gifs - Bonus/Biceps/rosca  direta no banco scort.jpg'),
  'Gifs - Bonus/Biceps/rosca alternada aparelho biarticular.gif': require('../../../../assets/thumbs/Gifs - Bonus/Biceps/rosca alternada aparelho biarticular.jpg'),
  'Gifs - Bonus/Biceps/rosca alternada pegada neutra sentado no banco.gif': require('../../../../assets/thumbs/Gifs - Bonus/Biceps/rosca alternada pegada neutra sentado no banco.jpg'),
  'Gifs - Bonus/Biceps/Rosca Concentrada 2.gif': require('../../../../assets/thumbs/Gifs - Bonus/Biceps/Rosca Concentrada 2.jpg'),
  'Gifs - Bonus/Biceps/rosca direta apaiada no banco barra W.gif': require('../../../../assets/thumbs/Gifs - Bonus/Biceps/rosca direta apaiada no banco barra W.jpg'),
  'Gifs - Bonus/Biceps/rosca direta barra pegada fechada sentado no banco.gif': require('../../../../assets/thumbs/Gifs - Bonus/Biceps/rosca direta barra pegada fechada sentado no banco.jpg'),
  'Gifs - Bonus/Biceps/rosca direta barra W.gif': require('../../../../assets/thumbs/Gifs - Bonus/Biceps/rosca direta barra W.jpg'),
  'Gifs - Bonus/Biceps/rosca neutra no banco scort aparelho.gif': require('../../../../assets/thumbs/Gifs - Bonus/Biceps/rosca neutra no banco scort aparelho.jpg'),
  'Gifs - Bonus/Biceps/rosca no banco scort barra W.gif': require('../../../../assets/thumbs/Gifs - Bonus/Biceps/rosca no banco scort barra W.jpg'),
  'Gifs - Bonus/Biceps/Rosca Scott Unil com Halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Biceps/Rosca Scott Unil com Halteres.jpg'),
  'Gifs - Bonus/Biceps/rosca unilateral com halteres sentado no banco.gif': require('../../../../assets/thumbs/Gifs - Bonus/Biceps/rosca unilateral com halteres sentado no banco.jpg'),
  'Gifs - Bonus/Costas/barra livre pegada aberta joelhos flexionados.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/barra livre pegada aberta joelhos flexionados.jpg'),
  'Gifs - Bonus/Costas/Barra Livre pegada aberta.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/Barra Livre pegada aberta.jpg'),
  'Gifs - Bonus/Costas/barra livre pegada pronada.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/barra livre pegada pronada.jpg'),
  'Gifs - Bonus/Costas/barra no graviton em pe.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/barra no graviton em pe.jpg'),
  'Gifs - Bonus/Costas/Hiperextensoes sem dispositivo (banco).gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/Hiperextensoes sem dispositivo (banco).jpg'),
  'Gifs - Bonus/Costas/levantamento terra no smith.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/levantamento terra no smith.jpg'),
  'Gifs - Bonus/Costas/pulley costa unilateral.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/pulley costa unilateral.jpg'),
  'Gifs - Bonus/Costas/pulley pegada aberta atras da nuca.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/pulley pegada aberta atras da nuca.jpg'),
  'Gifs - Bonus/Costas/pulley pegada aberta pronada.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/pulley pegada aberta pronada.jpg'),
  'Gifs - Bonus/Costas/remada aberta no banco inclinado com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/remada aberta no banco inclinado com halteres.jpg'),
  'Gifs - Bonus/Costas/remada baixa no pulley pegada aberta supinada.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/remada baixa no pulley pegada aberta supinada.jpg'),
  'Gifs - Bonus/Costas/remada baixa unilateral no cross.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/remada baixa unilateral no cross.jpg'),
  'Gifs - Bonus/Costas/remada cavalino com barra.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/remada cavalino com barra.jpg'),
  'Gifs - Bonus/Costas/remada inclinada no smith.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/remada inclinada no smith.jpg'),
  'Gifs - Bonus/Costas/remada inclinda no banco pegada supinda puxada fechada.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/remada inclinda no banco pegada supinda puxada fechada.jpg'),
  'Gifs - Bonus/Costas/remada livre  com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/remada livre  com halteres.jpg'),
  'Gifs - Bonus/Costas/remada no banco inclinado pegada pronada com barra.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/remada no banco inclinado pegada pronada com barra.jpg'),
  'Gifs - Bonus/Costas/remada unilateral cavalindo barra puxada fechada.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/remada unilateral cavalindo barra puxada fechada.jpg'),
  'Gifs - Bonus/Costas/voador invertido.gif': require('../../../../assets/thumbs/Gifs - Bonus/Costas/voador invertido.jpg'),
  'Gifs - Bonus/Membros Inferiores/adutora na tracao do cabo cross.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/adutora na tracao do cabo cross.jpg'),
  'Gifs - Bonus/Membros Inferiores/agachamento livre pes juntos.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/agachamento livre pes juntos.jpg'),
  'Gifs - Bonus/Membros Inferiores/agachamento na maquina.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/agachamento na maquina.jpg'),
  'Gifs - Bonus/Membros Inferiores/agachamento pes afastados.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/agachamento pes afastados.jpg'),
  'Gifs - Bonus/Membros Inferiores/agachamento sumo com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/agachamento sumo com halteres.jpg'),
  'Gifs - Bonus/Membros Inferiores/flex de joelho  em pe no cabo cross.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/flex de joelho  em pe no cabo cross.jpg'),
  'Gifs - Bonus/Membros Inferiores/Flexao Plantar com peso corporal.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/Flexao Plantar com peso corporal.jpg'),
  'Gifs - Bonus/Membros Inferiores/leg press pes afastados.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/leg press pes afastados.jpg'),
  'Gifs - Bonus/Membros Inferiores/levantamento terra com barra.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/levantamento terra com barra.jpg'),
  'Gifs - Bonus/Membros Inferiores/passada a frente com barra.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/passada a frente com barra.jpg'),
  'Gifs - Bonus/Membros Inferiores/passada com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/passada com halteres.jpg'),
  'Gifs - Bonus/Membros Inferiores/Retrocesso com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/Retrocesso com halteres.jpg'),
  'Gifs - Bonus/Membros Inferiores/stiff no smth.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/stiff no smth.jpg'),
  'Gifs - Bonus/Membros Inferiores/stiff unilateral com kettibel.gif': require('../../../../assets/thumbs/Gifs - Bonus/Membros Inferiores/stiff unilateral com kettibel.jpg'),
  'Gifs - Bonus/Ombro/Desenvolmento Frontal com Elastico.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/Desenvolmento Frontal com Elastico.jpg'),
  'Gifs - Bonus/Ombro/Desenvolvimento com Barra.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/Desenvolvimento com Barra.jpg'),
  'Gifs - Bonus/Ombro/Desenvolvimento com Halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/Desenvolvimento com Halteres.jpg'),
  'Gifs - Bonus/Ombro/desenvolvimento com rotacao.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/desenvolvimento com rotacao.jpg'),
  'Gifs - Bonus/Ombro/desenvolvimento no smith barra na nuca.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/desenvolvimento no smith barra na nuca.jpg'),
  'Gifs - Bonus/Ombro/Desenvolvimento por tras com barra.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/Desenvolvimento por tras com barra.jpg'),
  'Gifs - Bonus/Ombro/Desenvolvimento Sentado Smith.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/Desenvolvimento Sentado Smith.jpg'),
  'Gifs - Bonus/Ombro/desnvolvimento barra frente sentado.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/desnvolvimento barra frente sentado.jpg'),
  'Gifs - Bonus/Ombro/elevacao bilateral na maquina.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/elevacao bilateral na maquina.jpg'),
  'Gifs - Bonus/Ombro/Elevacao Frontal Crossover.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/Elevacao Frontal Crossover.jpg'),
  'Gifs - Bonus/Ombro/elevacao lateral inclinado sentado.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/elevacao lateral inclinado sentado.jpg'),
  'Gifs - Bonus/Ombro/elevacao unilateral frontal.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/elevacao unilateral frontal.jpg'),
  'Gifs - Bonus/Ombro/elevacao unilateral no cross.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/elevacao unilateral no cross.jpg'),
  'Gifs - Bonus/Ombro/remada livre com barra.gif': require('../../../../assets/thumbs/Gifs - Bonus/Ombro/remada livre com barra.jpg'),
  'Gifs - Bonus/Peito/crucifixo inclinado banco com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Peito/crucifixo inclinado banco com halteres.jpg'),
  'Gifs - Bonus/Peito/Crucifixo Maquina.gif': require('../../../../assets/thumbs/Gifs - Bonus/Peito/Crucifixo Maquina.jpg'),
  'Gifs - Bonus/Peito/Dumbbell covers com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Peito/Dumbbell covers com halteres.jpg'),
  'Gifs - Bonus/Peito/flex de cotovelo completa.gif': require('../../../../assets/thumbs/Gifs - Bonus/Peito/flex de cotovelo completa.jpg'),
  'Gifs - Bonus/Peito/flex de cotovelo declinado.gif': require('../../../../assets/thumbs/Gifs - Bonus/Peito/flex de cotovelo declinado.jpg'),
  'Gifs - Bonus/Peito/supino inclinado banco cross.gif': require('../../../../assets/thumbs/Gifs - Bonus/Peito/supino inclinado banco cross.jpg'),
  'Gifs - Bonus/Peito/supino inclinado banco no smith.gif': require('../../../../assets/thumbs/Gifs - Bonus/Peito/supino inclinado banco no smith.jpg'),
  'Gifs - Bonus/Peito/supino reto pegada aberta.gif': require('../../../../assets/thumbs/Gifs - Bonus/Peito/supino reto pegada aberta.jpg'),
  'Gifs - Bonus/Peito/voador maquina.gif': require('../../../../assets/thumbs/Gifs - Bonus/Peito/voador maquina.jpg'),
  'Gifs - Bonus/Trapezio/encolhimento livre com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Trapezio/encolhimento livre com halteres.jpg'),
  'Gifs - Bonus/Trapezio/encolhimento maquina.gif': require('../../../../assets/thumbs/Gifs - Bonus/Trapezio/encolhimento maquina.jpg'),
  'Gifs - Bonus/Trapezio/encolhimento na barra livre.gif': require('../../../../assets/thumbs/Gifs - Bonus/Trapezio/encolhimento na barra livre.jpg'),
  'Gifs - Bonus/Trapezio/encolhimento no smith.gif': require('../../../../assets/thumbs/Gifs - Bonus/Trapezio/encolhimento no smith.jpg'),
  'Gifs - Bonus/Trapezio/encolhimento pegada fechada barra no cross.gif': require('../../../../assets/thumbs/Gifs - Bonus/Trapezio/encolhimento pegada fechada barra no cross.jpg'),
  'Gifs - Bonus/Trapezio/encolhimento sentado no banco com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Trapezio/encolhimento sentado no banco com halteres.jpg'),
  'Gifs - Bonus/Trapezio/encolhimento sentado no banco inlinado com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Trapezio/encolhimento sentado no banco inlinado com halteres.jpg'),
  'Gifs - Bonus/Trapezio/remada alta com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Trapezio/remada alta com halteres.jpg'),
  'Gifs - Bonus/Trapezio/remada alta pegada abeta com barra.gif': require('../../../../assets/thumbs/Gifs - Bonus/Trapezio/remada alta pegada abeta com barra.jpg'),
  'Gifs - Bonus/Triceps/Apoio de frente pegada fechada parede.gif': require('../../../../assets/thumbs/Gifs - Bonus/Triceps/Apoio de frente pegada fechada parede.jpg'),
  'Gifs - Bonus/Triceps/arnold_dips-maschine.gif': require('../../../../assets/thumbs/Gifs - Bonus/Triceps/arnold_dips-maschine.jpg'),
  'Gifs - Bonus/Triceps/flex de cotovelo fechado livre.gif': require('../../../../assets/thumbs/Gifs - Bonus/Triceps/flex de cotovelo fechado livre.jpg'),
  'Gifs - Bonus/Triceps/flex de cotovelo fechado.gif': require('../../../../assets/thumbs/Gifs - Bonus/Triceps/flex de cotovelo fechado.jpg'),
  'Gifs - Bonus/Triceps/supino declinado no smit.gif': require('../../../../assets/thumbs/Gifs - Bonus/Triceps/supino declinado no smit.jpg'),
  'Gifs - Bonus/Triceps/Supino declinado pegada fechada.gif': require('../../../../assets/thumbs/Gifs - Bonus/Triceps/Supino declinado pegada fechada.jpg'),
  'Gifs - Bonus/Triceps/triceps na paralela maquiba.gif': require('../../../../assets/thumbs/Gifs - Bonus/Triceps/triceps na paralela maquiba.jpg'),
  'Gifs - Bonus/Triceps/triceps paralelo no banco.gif': require('../../../../assets/thumbs/Gifs - Bonus/Triceps/triceps paralelo no banco.jpg'),
  'Gifs - Bonus/Triceps/triceps patada unilateral com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Triceps/triceps patada unilateral com halteres.jpg'),
  'Gifs - Bonus/Triceps/Triceps testa com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Triceps/Triceps testa com halteres.jpg'),
  'Gifs - Bonus/Triceps/triceps tresta com halteres.gif': require('../../../../assets/thumbs/Gifs - Bonus/Triceps/triceps tresta com halteres.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Afundo cruzando perna de tras.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Afundo cruzando perna de tras.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Afundo lateral com barra.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Afundo lateral com barra.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Agachamento frontal 02.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Agachamento frontal 02.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Agchamento smith.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Agchamento smith.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Avanco com barra.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Avanco com barra.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Aviao unilateral.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Aviao unilateral.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/band-standing-hip-extension.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/band-standing-hip-extension.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/barbell-good-morning.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/barbell-good-morning.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/barbell-hip-thrust.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/barbell-hip-thrust.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/barbell-romanian-deadlift-movement.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/barbell-romanian-deadlift-movement.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Cadeira adutora.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Cadeira adutora.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Clean.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Clean.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/ELEVACAO PELVICA APOIO UNILATERAL.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/ELEVACAO PELVICA APOIO UNILATERAL.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Elevacao pelvica pes elevados.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Elevacao pelvica pes elevados.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Elevacao pelvica.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Elevacao pelvica.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Extensao 6 apoios.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Extensao 6 apoios.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Extensao de quadril 01.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Extensao de quadril 01.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Flexao nordica.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Flexao nordica.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Flexora em pe unilateral.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Flexora em pe unilateral.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/frog-pump.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/frog-pump.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Front squat.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Front squat.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/glute-bridge.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/glute-bridge.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Good morning.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Good morning.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Leg press 45.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Leg press 45.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Mesa flexora.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Mesa flexora.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Passadas com halteres.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Passadas com halteres.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Pistol 02.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Pistol 02.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Recuo.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Recuo.jpg'),
  'MEMBROS INFERIORES E GLÚTEOS (1)/Stiff com halteres.gif': require('../../../../assets/thumbs/MEMBROS INFERIORES E GLÚTEOS (1)/Stiff com halteres.jpg'),
  'PANTURRILHA (1)/seated-calf-raise-dumbbell.gif': require('../../../../assets/thumbs/PANTURRILHA (1)/seated-calf-raise-dumbbell.jpg'),
  'PEITORAL (1)/barbell-decline-bench-press.gif': require('../../../../assets/thumbs/PEITORAL (1)/barbell-decline-bench-press.jpg'),
  'PEITORAL (1)/bench-press-feet-up.gif': require('../../../../assets/thumbs/PEITORAL (1)/bench-press-feet-up.jpg'),
  'PEITORAL (1)/cable-cross-over.gif': require('../../../../assets/thumbs/PEITORAL (1)/cable-cross-over.jpg'),
  'PEITORAL (1)/chest-press-machine.gif': require('../../../../assets/thumbs/PEITORAL (1)/chest-press-machine.jpg'),
  'PEITORAL (1)/Cross over 1.gif': require('../../../../assets/thumbs/PEITORAL (1)/Cross over 1.jpg'),
  'PEITORAL (1)/Cross over 2.gif': require('../../../../assets/thumbs/PEITORAL (1)/Cross over 2.jpg'),
  'PEITORAL (1)/Cross over polia baixa.gif': require('../../../../assets/thumbs/PEITORAL (1)/Cross over polia baixa.jpg'),
  'PEITORAL (1)/Crucifico com halteres.gif': require('../../../../assets/thumbs/PEITORAL (1)/Crucifico com halteres.jpg'),
  'PEITORAL (1)/Crucifixo inclinado com halteres.gif': require('../../../../assets/thumbs/PEITORAL (1)/Crucifixo inclinado com halteres.jpg'),
  'PEITORAL (1)/Crucifixo inclinado no cabo 2.gif': require('../../../../assets/thumbs/PEITORAL (1)/Crucifixo inclinado no cabo 2.jpg'),
  'PEITORAL (1)/CRUCIFIXO POLIA BAIXA.gif': require('../../../../assets/thumbs/PEITORAL (1)/CRUCIFIXO POLIA BAIXA.jpg'),
  'PEITORAL (1)/Declinado smith.gif': require('../../../../assets/thumbs/PEITORAL (1)/Declinado smith.jpg'),
  'PEITORAL (1)/decline-cable-fly.gif': require('../../../../assets/thumbs/PEITORAL (1)/decline-cable-fly.jpg'),
  'PEITORAL (1)/dumbbell-chest-press.gif': require('../../../../assets/thumbs/PEITORAL (1)/dumbbell-chest-press.jpg'),
  'PEITORAL (1)/dumbbell-one-arm-chest-press.gif': require('../../../../assets/thumbs/PEITORAL (1)/dumbbell-one-arm-chest-press.jpg'),
  'PEITORAL (1)/Flexao apoio alto banco.gif': require('../../../../assets/thumbs/PEITORAL (1)/Flexao apoio alto banco.jpg'),
  'PEITORAL (1)/Flexao assistida.gif': require('../../../../assets/thumbs/PEITORAL (1)/Flexao assistida.jpg'),
  'PEITORAL (1)/high-cable-fly.gif': require('../../../../assets/thumbs/PEITORAL (1)/high-cable-fly.jpg'),
  'PEITORAL (1)/INCLINADO NO SMITH.gif': require('../../../../assets/thumbs/PEITORAL (1)/INCLINADO NO SMITH.jpg'),
  'PEITORAL (1)/incline-barbell-bench-press.gif': require('../../../../assets/thumbs/PEITORAL (1)/incline-barbell-bench-press.jpg'),
  'PEITORAL (1)/low-cable-chest-flys.gif': require('../../../../assets/thumbs/PEITORAL (1)/low-cable-chest-flys.jpg'),
  'PEITORAL (1)/Paralelas graviton.gif': require('../../../../assets/thumbs/PEITORAL (1)/Paralelas graviton.jpg'),
  'PEITORAL (1)/Peck deck.gif': require('../../../../assets/thumbs/PEITORAL (1)/Peck deck.jpg'),
  'PEITORAL (1)/pike-push-up.gif': require('../../../../assets/thumbs/PEITORAL (1)/pike-push-up.jpg'),
  'PEITORAL (1)/Press alto inclinado.gif': require('../../../../assets/thumbs/PEITORAL (1)/Press alto inclinado.jpg'),
  'PEITORAL (1)/Press peitoral 3.gif': require('../../../../assets/thumbs/PEITORAL (1)/Press peitoral 3.jpg'),
  'PEITORAL (1)/push-up-bars.gif': require('../../../../assets/thumbs/PEITORAL (1)/push-up-bars.jpg'),
  'PEITORAL (1)/SUPINO ALTERNADO COM HALTERES.gif': require('../../../../assets/thumbs/PEITORAL (1)/SUPINO ALTERNADO COM HALTERES.jpg'),
  'PEITORAL (1)/Supino barra.gif': require('../../../../assets/thumbs/PEITORAL (1)/Supino barra.jpg'),
  'PEITORAL (1)/Supino incliando com halteres.gif': require('../../../../assets/thumbs/PEITORAL (1)/Supino incliando com halteres.jpg'),
  'PEITORAL (1)/Supino inclinado.gif': require('../../../../assets/thumbs/PEITORAL (1)/Supino inclinado.jpg'),
  'PEITORAL (1)/Supino smith.gif': require('../../../../assets/thumbs/PEITORAL (1)/Supino smith.jpg'),
  'TRÍCEPS (1)/bench-tricep-dips.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/bench-tricep-dips.jpg'),
  'TRÍCEPS (1)/cable-tricep-kickback.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/cable-tricep-kickback.jpg'),
  'TRÍCEPS (1)/close-grip-bench-press-movement.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/close-grip-bench-press-movement.jpg'),
  'TRÍCEPS (1)/overhead-cable-tricep-extension.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/overhead-cable-tricep-extension.jpg'),
  'TRÍCEPS (1)/Paralelas no graviton.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/Paralelas no graviton.jpg'),
  'TRÍCEPS (1)/Triceps extensao unilateral.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/Triceps extensao unilateral.jpg'),
  'TRÍCEPS (1)/Triceps frances barra w.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/Triceps frances barra w.jpg'),
  'TRÍCEPS (1)/Triceps frances inclinado com halter.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/Triceps frances inclinado com halter.jpg'),
  'TRÍCEPS (1)/Triceps frances unilateral cabo.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/Triceps frances unilateral cabo.jpg'),
  'TRÍCEPS (1)/Triceps frances.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/Triceps frances.jpg'),
  'TRÍCEPS (1)/Triceps maquina 01.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/Triceps maquina 01.jpg'),
  'TRÍCEPS (1)/Triceps maquina 02.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/Triceps maquina 02.jpg'),
  'TRÍCEPS (1)/Triceps pulley.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/Triceps pulley.jpg'),
  'TRÍCEPS (1)/Triceps testa 01.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/Triceps testa 01.jpg'),
  'TRÍCEPS (1)/Triceps testa unilateral.gif': require('../../../../assets/thumbs/TRÍCEPS (1)/Triceps testa unilateral.jpg'),
};
